name: "guardian/riff-raff-checksum"
description: "Compare two builds to check if they are identical."
inputs:
  projectName:
    description: The name of the project as it appears on Riff-Raff
    required: true
  teamCityMainBuildNumber:
    description: The TeamCity build number (last build on the main branch)
    required: true
  currentBuildNumber:
    description: The current build number from GitHub Actions (including TeamCity offset)
    required: false
  
runs:
  using: "composite"
  steps:
    - name: Do we need this
      uses: actions/checkout@v3

    - name: Get AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GU_RIFF_RAFF_READ_ARN }}
        aws-region: eu-west-1

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install Python dependencies
      run: pip install -r requirements.txt
      shell: bash
      
    - name: Run the compare script
      run: python3 compare.py ${{ inputs.projectName }} ${{ inputs.teamCityMainBuildNumber }} ${{ inputs.currentBuildNumber }} 
      shell: bash
      
